runtime: nodejs10
service: default
inbound_services:
  - warmup

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  TS_NODE_PROJECT: './tsconfig.dist.json'
  APP_ENV: 'prod'
