#
# validate yml:
# circleci config validate
#
version: 2.1

#
# Orbs
#
orbs:
  tools: naturalcycles/tools@volatile
  # tools: naturalcycles/tools@dev:1

#
# Jobs
#
jobs:
  build-deploy-job:
    executor: tools/node-gcloud
    steps:
      - checkout
      - run: echo 'export GIT_MSG=`git log -1 --pretty=%B`' >> $BASH_ENV

      # Yarn
      - tools/install_yarn_deps

      # Deploy
      - run:
          name: Deploy
          command: |
            yarn build-prod
            yarn prepareDeploy
            gcloud version
            echo $GCP_SERVICE_ACCOUNT | gcloud auth activate-service-account --key-file=-
            yarn deploy

      - run:
          name: Validate deployment
          command: |
            curl --fail https://kg-backend2.appspot.com/ || exit 1

#
# Workflows
#
workflows:
  version: 2

  build-workflow:
    jobs:
      - build-deploy-job:
          filters:
            branches:
              only: master
      - tools/test-lib-job:
          CC_TEST_REPORTER_ID: 16d16f012b65f3ddc9161380fb236188a60a403f12c71d62719f9f9605851ba8
